[project]
name = "chat-empresas"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "beautifulsoup4>=4.12.3",
    "requests>=2.32.3",
    "streamlit>=1.41.1",
]
